# Generated by Django 3.2.3 on 2021-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, unique=True)),
                ('pays', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'joueurs',
                'managed': False,
            },
        ),
    ]
